# Generated by Django 4.0 on 2022-01-25 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.IntegerField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('state', models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
