# Generated by Django 4.0 on 2022-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='pizza/')),
                ('State', models.IntegerField(choices=[{0, 'disable'}, {1, 'enable'}], default=0)),
                ('type', models.IntegerField(choices=[{0, 'Pizza'}, {1, 'Slice'}, {'Roll', 2}], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Ingredients', models.ManyToManyField(to='menu.Ingredients')),
            ],
        ),
    ]
