# Generated by Django 4.0 on 2022-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('state', models.IntegerField(choices=[{0, 'disable'}, {'enable', 1}], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('state', models.IntegerField(choices=[{0, 'disable'}, {'enable', 1}], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='Ingredients',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(to='menu.Ingredient'),
        ),
    ]
