# Generated by Django 4.0 on 2022-01-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingredient_type_rename_state_pizza_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.type'),
        ),
    ]
